#!/usr/bin/env bash
# [MISE] description="Verify Grafana NodePort is accessible"

set -e

echo "Grafana service:"
kubectl get svc kube-prometheus-stack-grafana -n monitoring
echo ""
NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
echo "Access URL: http://${NODE_IP}:30030"
echo "Get admin password: kubectl get secret kube-prometheus-stack-grafana -n monitoring -o jsonpath='{.data.admin-password}' | base64 -d"
