#!/usr/bin/env bash
# [MISE] description="Template kube-prometheus-stack without deploying"

set -e

TEMPLATE_FILE=$(mktemp -t stack-template-XXXXXX.yaml)
helmfile -f helmfile.yaml -l name=kube-prometheus-stack template > "$TEMPLATE_FILE"
echo "Template written to: $TEMPLATE_FILE"
echo "Lines: $(wc -l < $TEMPLATE_FILE)"
